import logging

LOGGER_NAME = 'app_logger'


def create_logger():

    # Creates the Logger (to record program events)
    logger = logging.getLogger(LOGGER_NAME)
    # Sets the logger level to DEBUG
    # (detailed information for diagnosing problems)
    logger.setLevel(logging.DEBUG)

    # Creates the format of messages generated by the Logger
    formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")

    # Creates a 'file_handler' manipulation console
    # (which sends the appropriate messages)
    file_handler = logging.FileHandler("app.log")
    # Sets the console level to INFO
    # (to confirm that things are working as expected)
    file_handler.setLevel(logging.INFO)
    # Adds the format to the 'file_handler'
    file_handler.setFormatter(formatter)

    # Creates a 'stream_handler' manipulation console
    stream_handler = logging.StreamHandler()
    # Adds the format to the 'stream_handler'
    stream_handler.setFormatter(formatter)
    # Sets the console level to DEBUG
    # (detailed information for diagnosing problems)
    stream_handler.setLevel(logging.DEBUG)

    # Adds 'file_handler' and 'stream_handler' to the Logger
    logger.addHandler(file_handler)
    logger.addHandler(stream_handler)
